---
jobs:

  - job_name: A_job
    pipeline_name: first_pipe
    agent_address: petitprince-16.luxembourg.grid5000.fr
    source_broker: [petitprince-15.luxembourg.grid5000.fr] # upstream broker address, number should be equal to number of source topics
    source_topic: [T-1]
    sink_broker: [petitprince-9.luxembourg.grid5000.fr] # downstream broker address, number should be equal to number of sink topics
    sink_topic: [T-2]
    entry_class: agentpackage.MultiSourceTest
    job_path: ../jars/flinktest-1.jar